Destination zeros from eltype in zero-length generic_matvecmul (#1241)
This fixes issues like
```julia
julia> A = fill(@SMatrix(zeros(2,2)), 4, 0)
4×0 Matrix{SMatrix{2, 2, Float64, 4}}

julia> v = fill(@SMatrix(zeros(2,2)), size(A,2))
SMatrix{2, 2, Float64, 4}[]

julia> A * v
ERROR: MethodError: Cannot `convert` an object of type Bool to an object of type SMatrix{2, 2, Float64, 4}
The function `convert` exists, but no method is defined for this combination of argument types.
[...]
```